name: Mutants

on: push

jobs:
  cargo_mutants:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-mutants
        run: cargo install --locked cargo-mutants

      - name: Run mutation tests
        run: cargo mutants --gitignore false --no-shuffle

      - name: Archive results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: mutation-report
          path: rust/mutants.out
